### ISSUE TITLE
Update FEES NORAD number (and hence TLE's?)

### ISSUE THREAD

**Issue by mahtin** [G4lile0/tinyGS#111]
Presently the `norad` number used for **FEES** is `99738`.

Looking at http://www.planet4589.org/space/log/satcat.txt I see `48082` listed for FEES. 
```
S048082 2021-022AL     FEES                              ?      FEES                     GPAP         2021 Mar 22 In Earth orbit                2021 Apr  1 LLEO/S      95.59    537 x    558 x  97.56
```
Sadly https://www.celestrak.com/pub/satcat.txt only marks it as `OBJECT AL`.
```
2021-022AL   48082     OBJECT AL                 TBD    2021-03-22  TYMSC                 95.6   97.6     558     535     N/A       
```

If this is the correct satellite; then I believe the `norad` number should be updated in the packet data. Plus, looking at https://heavens-above.com/orbit.aspx?satid=48082 I would suspect that the `TLE`'s are:
```
1 48082U 21022AL  21152.01156273  .00002152  00000-0  14918-3 0  9991
2 48082  97.5606  54.5896 0016358   4.3765 121.4198 15.06571919  9102
```

(Update)
I see that the `norad` number is correctly listed on https://tinygs.com/satellite/FEES page; however, that isn't reflected in the packet data.

**Comment by G4lile0** [comment]
Thanks Martin for pointing it, packets `norad` number is amended now  from  `99738` to `48082`
