### ISSUE TITLE
Wiki Typos: FAQ

### ISSUE THREAD

**Issue by jimt** [G4lile0/tinyGS#114]
> I'm new and I want to get in, what hardware should I buy? Fist choose the satellites that you want to receive.

Fist -> First

> What type of anntenna should I use for TinyGS LoRa is an awesome technology and can receive signals under the noise floor. The standard duck or coil antennas that usually come with Heltec or TTGO boards were proven to receive some packets form quite long distances. However, the conditions have to be good to be able to receive with such 

anntenna -> antenna
form -> from

**Comment by 4m1g0** [comment]
Hello, Thanks for the review!

Can you edit it here? https://github.com/4m1g0/tinygs-wiki/blob/master/FAQ.md

Just click on the edit button and then send the changes proposal, that way the contribution is registered.

![image](https://user-images.githubusercontent.com/204293/121547349-59cda600-ca0c-11eb-896d-ee563ca7c8b6.png)

**Comment by jimt** [comment]
Done in 4m1g0/tinygs-wiki#5

Sorry, I had looked for the wiki under G4lile0.
