### ISSUE TITLE
Website binary transmission input cannot contain 0s

### ISSUE THREAD

**Issue by jgromes** [G4lile0/tinyGS#124]
It seems that the validation of input on the tinygs.com website doesn't allow zeroes to be entered. For an example, see the screenshot below:

![tinygs](https://user-images.githubusercontent.com/3407192/131180679-4c22c75e-a1e9-486f-84bd-101b918a6af6.png)

In addition, the input text field will attempt to "auto-correct" any zeroes entered, so it's not possible to enter e.g 0x01 0x02 - it will get auto-corrected to 0x12.

PS: I'm not sure if this is the correct place to report this - please let me know if not.

**Comment by 4m1g0** [comment]
Thanks a lot Jan,

I've made a quick fix and it should be working properly now. Let me know if it's not the case!

**Comment by jgromes** [comment]
And thank you for the prompt bugfix, it is indeed all OK now.

**Comment by 4m1g0** [comment]
In case you had more problems with the TX, I've just finally had time to test it and found another bug related to the hex TX, under certain circumstances it was sending a wrong base64 str to the network so the tx string that received the board was not the right one.

It should be fixed now.

**Comment by jgromes** [comment]
Thanks, I was only using the direct hex input, and didn't notice any issues with that.
