### ISSUE TITLE
Packetview on www.tinygs.com not working After added a Second  station

### ISSUE THREAD

**Issue by andreSai** [G4lile0/tinyGS#127]
scince 25.august 2021 my packetview in  station info on www.tinygs.com has no data. On this day i have added a second station. the station-names are DL4INA_GS and DL4INA_GS_2 . all other things working good. Please fix this issue, or give me a tipp to resolve the problem, if possible.

**Comment by 4m1g0** [comment]
Seems that now it's working, please reopen if it persists.
