### ISSUE TITLE
Ground Station Arduino Code for ESP32 and Lora board without the OLED

### ISSUE THREAD

**Issue by Cloolalang** [G4lile0/tinyGS#13]
I am in South Africa, I am ready to setup my ground station but I dont have a Heltec or TTGO board...
I have an ESP32 Dev Board with an AI thinker RA02 for Lora at 433Mhz it is working and is based in this:

https://randomnerdtutorials.com/esp32-lora-rfm95-transceiver-arduino-ide/

Is there a version of the ground station Arduino firmware without the OLED stuff?

**Comment by Cloolalang** [comment]
All Good I just deleted out all the oLED stuff

**Comment by 4m1g0** [comment]
Hello, thanks for the info.

It could be interesting to add a flag to disable the OLED in configuration for all the boards that do not have it.

**Comment by lillefyr** [comment]
It would be nice to have all the configurable parameters in one file.  I use a Lolin D32 v1.0 board,

**Comment by G4lile0** [comment]
Fixed on the new release
