### ISSUE TITLE
Beta 2202126 is missing settings in the board configuration settings.  

### ISSUE THREAD

**Issue by JasonRJ** [G4lile0/tinyGS#142]
I know this is not the current focus.  Just what I noticed.

![tinyGS 2105262 (current)](https://user-images.githubusercontent.com/3704942/153890155-aaa8573d-d1d3-4c40-b125-e8fcac5cce32.png)

![tinyGS 2112021 (beta)](https://user-images.githubusercontent.com/3704942/153890249-82415560-b561-47db-a38d-69a3f09aa672.png)

**Comment by 4m1g0** [comment]
Those are moved to the tinygs.com web panel, so they are all in one place for clarity.
