### ISSUE TITLE
2,4GHz GS Configuration

### ISSUE THREAD

**Issue by Leila49** [G4lile0/tinyGS#144]
hey , I was wondering if the TinyGS community supports an ESP32+SX1280 LoRa tranceiver for tracking satellites on 2?4GHz

**Comment by G4lile0** [comment]
Sure, it's already supported on the beta branch.
 
https://github.com/G4lile0/tinyGS/tree/beta

**Comment by Leila49** [comment]
Okey,thanks. 
And for the board configuration , can we do it with the quick start , or we have to program it plz ?

**Comment by G4lile0** [comment]
Here you have the board configuration, that iIm using for the ESP32+SX1280 :

`{"name":"[2.4] Multi SX1280","aADDR":60,"oSDA":21,"oSCL":22,"oRST":16,"pBut":0,"led":22,"radio":8,"lNSS":5,"lDIO0":26,"lDIO1":34,"lBUSSY":32,"lRST":14,"lMISO":19,"lMOSI":27,"lSCK":18,"lTCXOV":0.0}`
