### ISSUE TITLE
Question over a board

### ISSUE THREAD

**Issue by WaldperlachFabi** [G4lile0/tinyGS#145]
Hello, im not so good in programming etc. but i would like to create my own tinyGS. My Question is whether [this](https://www.amazon.de/dp/B08CGSYM4G/ref=cm_sw_em_r_mt_dp_569BA0XW7W79969KSP74) Board is supported and if i have to buy something else. (I have a micro usb cable). Thank you for your help and your nice Project!

**Comment by G4lile0** [comment]
yep, it's supported .
