### ISSUE TITLE
OLED not responding to JSON file changes

### ISSUE THREAD

**Issue by gotfredsen** [G4lile0/tinyGS#146]
I have this JSON line
```json
{"name":"[433] Domino4","aADDR":60,"oSDA":26,"oSCL":27,"oRST":0,"pBut":0,"led":0,"radio":1,"lNSS":15,"lDIO0":33,"lDIO1":0,"lBUSSY":0,"lRST":0,"lMISO":12,"lMOSI":13,"lSCK":14,"lTCXOV":0.0}
```
but the OLED is just blank. Radio so far (sending and receiving test packets), and everything else is working fine, but not the OLED.

I did this change in `Display.cpp`, which obviously is wrong just to see if I was going nuts. 
```c
  //display = new SSD1306(board.OLED__address, board.OLED__SDA, board.OLED__SCL);
    display = new SSD1306(60, 26, 27);
```
and now it works! ...but this is obviously not the way.

**Comment by 4m1g0** [comment]
We have not been able to reproduce this. The values passed to the display are exactly the ones defined on the json string.

Be aware that the oRST must also be the right pin otherwise it wont work. It's usually pin 16, not 0!!
