### ISSUE TITLE
TBeam 915 defaults to 433 on custom board upload

### ISSUE THREAD

**Issue by PeterJBurke** [G4lile0/tinyGS#149]
I have 915 hardware, but when using the board template it defaults to 433. The board template does not have an entry for the frequency. How do I set the software up to know that it is 915 hardware for the custom board option?

Board:
LILYGO® TTGO Meshtastic T-Beam V1.1 ESP32 LoRa 433/868/915/923Mhz Wireless Module WiFi GPS NEO-6M With OLED Display for Arduino

Board template I used:
{"name":"T-beam v1.1 + oled","aADDR":60,"oSDA":21,"oSCL":22,"pBut":38,"led":14,"radio":1,"lNSS":18,"lDIO0":26,"lRST":23,"lMISO":19,"lMOSI":27,"lSCK":5,"lTCXOV":0.0}

**Comment by 4m1g0** [comment]
The initial radio configuration in the firmware is for 433 as the firmware is the same for all the boards. Once configured you can operate your tinygs though the web and set autotune or manual configuration for the right frequency:

https://youtu.be/beyejco3UMo?t=169
