### ISSUE TITLE
Custom board template repeatedly re-parsed

### ISSUE THREAD

**Issue by mdkendall** [G4lile0/tinyGS#154]
If a custom board template is entered in the configuration, then `ConfigManager::getBoardConfig()` calls `ConfigManager::parseBoardTemplate()` to parse it using ArduinoJson, which is fairly expensive.

But it turns out `getBoardConfig()` is called a lot. Specifically, `checkButton()` calls it every time to discover the button pin, and `checkButton()` is called repeatedly in the main loop.

I set and cleared a GPIO pin inside `parseBoardTemplate()` and viewed it with a logic analyser. I measured `parseBoardTemplate()` being called 300 times per second and taking about 380us each time, consuming about 11% of the total CPU power.

![parseBoardTemplate](https://user-images.githubusercontent.com/667844/167278250-abef757a-ee49-4580-896a-361ebb4efc5e.png)

It would be better if `getBoardConfig()` called `parseBoardTemplate()` once and cached the result.

**Comment by 4m1g0** [comment]
Thanks for the detailed description of this problem. It should be fixed now in beta.
