### ISSUE TITLE
[SUGGESTION] GitHub Discussions for TinyGS

### ISSUE THREAD

**Issue by MannyPeterson** [G4lile0/tinyGS#167]
Would the project maintainers be open to turning on [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) for TinyGS? GitHub Discussions can't replace the Telegram bot but it sure would be a more effective means of discussing the project. For example, if I wanted to learn about LNAs, antennas, etc., today I cannot go to one place and read what has been discussed. I have to re-ask the question in the hope that the right people are on Telegram to answer my question. Just a suggestion. :)

**Comment by tkerby** [comment]
Completely agree with this! Would also be a good way to create content for the wiki where useful like a summary of antenna discussions or solar options
