### ISSUE TITLE
Support ESP32S2

### ISSUE THREAD

**Issue by tkerby** [G4lile0/tinyGS#171]
For people building their own nodes, the S2 is a nice low cost option. Unfortunately, the SPI mappings are slightly different and VSPI has been swapped with FSPI. Could this be a compile option in the code?

Only challenge may be auto-updates as they might need two binary files depending on the board

**Comment by G4lile0** [comment]
We just added support ESP32S3 on the beta branch and yep it handle SPI in a different way.
