### ISSUE TITLE
API docs typo

### ISSUE THREAD

**Issue by thetazero** [G4lile0/tinyGS#179]
I noticed a slight typo in the [api docs](https://github.com/G4lile0/tinyGS/wiki/Programmatic-API#endpoitns):
![Screenshot from 2022-08-15 14-45-52](https://user-images.githubusercontent.com/28244551/184696803-3de247ec-098b-4cc6-88b1-8c6b2c10d583.png)

"Endpoints" is spelled "Endpoitns".

I don't believe I can open a pull for wiki so I figured I'd drop this here.

**Comment by G4lile0** [comment]
Thanks for pointing it, I just fixed it.
