### ISSUE TITLE
HiLetgo ESP32 LoRa SX1278 V3 board support needed

### ISSUE THREAD

**Issue by logictechs** [G4lile0/tinyGS#193]
I recently purchased a HiLetgo ESP32 LoRa SX1278 V3 board from Amazon.  I assumed it would be supported by TinyGS firmware and PC loader application but it is not.  The PC loader application simply shuts down when trying to load the firmware.  I was finally able to successfully compile and attempt loading the firmware using latest Arduino IDE but the firmware causes a boot loop and won't work.  Any help would be much appreciated.

**Comment by 27thfile** [comment]
Same issue here with the Heltec V3. For the record, I knew the V3 wasn't supported and thought I was buying a V2 based on the listing pictures :).

**Comment by logictechs** [comment]
I was able to finally get it to not boot loop loading some different test programs.  It seems to not be able to communicate with the LoRa chip though.  I'm trying to find an accurate schematic to determine if it's a pin reassignment issue.  Apparently, the ESP32 chip on the board has 4 SPI ports but only 2 are implemented so far in the ESP-IDF.
Can you confirm the V2 or V1 actually work with the TinyGS firmware?

**Comment by 27thfile** [comment]
I can't confirm from personal experience, but they are listed as supported boards.

"Currently we are officially supporting the following proven LoRa boards:

Heltec WiFi LoRa 32 V1 (433MHz & 863-928MHz versions)
Heltec WiFi LoRa 32 V2 (433MHz & 863-928MHz versions)"

**Comment by Rustie0125** [comment]
You are facing a multifaceted problem, the current TinyGS firmware has issues in that the board profile that gets set via the web interface does not properly relate to the actual pins you think they do. so there is that unknown, Using the customer board profile templete only makes things worse. for instance NSS pin should be able to be mapped to any pin since its a gpio... wrong. Only pin 5 works. then to makes things more complicated. the RadioLib is outdated and with recent issues pickeup that sometimes sx1262 /61 /68 can be confused with each other, your TinyGS might mistake the chip and report error code -2 which relates to SPI issues but in fact its just the default response when the device cannot reach the expected chip that was selected. This is ongoing issue and only way I found to implement or force change is to use arduino or plateform.io and change the pin outs in the config.h and cpp files before compiling but that does not solve the IC being miss identified. in short tinygs code base needs work, alot of work.

**Comment by 27thfile** [comment]
Thanks for your comment Rustie0125. I'll continue to monitor this space for any future updates, but for now I just simply don't have the time to work through the issues.

**Comment by kombjuder** [comment]
The Problem looks like it is the new MCU ESP32V3. PlatformIO tells en error:

 This chip is ESP32-S3(beta3) not ESP32. Wrong --chip argument?

**Comment by MattCurryCom** [comment]
Sketch uses 249530 bytes (19%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13600 bytes (4%) of dynamic memory, leaving 314080 bytes for local variables. Maximum is 327680 bytes.
Sketch uses 249530 bytes (19%) of program storage space. Maximum is 1310720 bytes.
Global variables use 13600 bytes (4%) of dynamic memory, leaving 314080 bytes for local variables. Maximum is 327680 bytes.
esptool.py v3.0-dev
Serial port /dev/ttyUSB0
Connecting....
WARNING: This chip doesn't appear to be a ESP32 (date codes 0x03700000:0x00000000). Probably it is unsupported by this version of esptool.
Chip is ESP32-D0WDQ6 (revision 0)
Features: WiFi, BT, Dual Core, Coding Scheme None
WARNING: Detected crystal freq 0.00MHz is quite different to normalized freq 26MHz. Unsupported crystal in use?
Crystal is 26MHz
MAC: 00:00:00:00:00:00
Uploading stub...
Running stub...

A fatal error occurred: Invalid head of packet (0x47)
A fatal error occurred: Invalid head of packet (0x47)

**Comment by sardonyxserendil** [comment]
There's no v2 boards out there, I ended up getting a v3 board without knowing it was unsupported.  I'm also receiving the error: A fatal error occurred: Invalid head of packet (0x47)

When using the TinyGS Uploader.  When can we expect v3 to be supported?

**Comment by RattyDAVE** [comment]
Trying to get hold a V2 board is now impossible. I ordered what I thought was a V2 board and got a V3. So just a word of caution.

**Comment by sasaga** [comment]
Someone found something for this version, the same thing happened to me v3.
`A fatal error occurred: This chip is ESP32-S3(beta3) not ESP32. Wrong --chip argument?`

**Comment by tremmert81** [comment]
Confirmed.  I ordered 1 from amazon, v3.  I ordered 2 from Alibaba, and they were also v3.

**Comment by awatchar** [comment]
I bought 6 pcs Heltec LoRa V3 by mistake. 😭😭
May be I should go back for TTGO LoRa and TTGO T-beam because Heltec LoRa V2 is out of market now.

**Comment by G4lile0** [comment]
Beta branch now support Heltec LoRa V3 (ESP32S3).

**Comment by RattyDAVE** [comment]
This is fantastic news!

**Comment by sudhanvasp** [comment]
Anyone having connectivity issues on the beta branch with Heltec LoRA V3 or has it been smooth sailing? The open wifi shuts down before I can set up the config details in the page for me.

**Comment by TechSully** [comment]
Where is the beta branch located?  Noob here... I'd like to try my Heltec LoRA V3 (as others have mentioned the v2 boards are very scarce and can't be found).
Thx!
Sully

**Comment by sudhanvasp** [comment]
The link to beta branch:  [https://github.com/G4lile0/tinyGS/tree/beta](https://github.com/G4lile0/tinyGS/tree/beta)
I'd however suggest you to take a look at the telegram channel. [https://t.me/joinchat/DmYSElZahiJGwHX6jCzB3Q](https://t.me/joinchat/DmYSElZahiJGwHX6jCzB3Q)
