### ISSUE TITLE
v2308041 - beta ||  OLED display off/black after code upload

### ISSUE THREAD

**Issue by K4KDR** [G4lile0/tinyGS#201]
Using the same TTGO ESP32 hardware that has been working since day-1 with previous tinyGS code (https://www.aliexpress.us/item/2251832729579512.html), I attempted to load the new BETA branch ( https://github.com/G4lile0/tinyGS/commit/1d776f5de3760af9a1bc1631276757d7426fe361 ) .

After upload, the OLED display was all black.  Only accessing the serial monitor in VSCode gave any indication that tinyGS code was loaded.   As mentioned in another ISSUE  ( https://github.com/G4lile0/tinyGS/issues/200 ), an older 'Platform' setting was required to get to a normal boot screen.   But whether stuck in a boot loop or in a successful, normal boot, there was no OLED display.

However, once the device was configured via HTTP / 192.168.4.1, **the OLED display functioned normally**.    Previous versions of code used the OLED display to instruct the user to connect via Wi-Fi + 192.168.4.1 to configure the device after code was uploaded.

Thanks!

-Scott,  K4KDR

**Comment by G4lile0** [comment]
Thanks for the feedback, it's fixed now.
