### ISSUE TITLE
Setting Lora SW from Remote is Incorrect

### ISSUE THREAD

**Issue by ronyronen** [G4lile0/tinyGS#210]
There's a typo in the `tinyGS/src/Mqtt/MQTT_Client.cpp` file. It's currently checking for `commandCrc`, but it seems the intention is to check for `commandLsw` instead.

```
  // Remote_LoRa_syncword [8,1,2,3,4,5,6,7,8,9]
  if (!strcmp(command, commandCrc))
    result = radio.remote_lsw((char *)payload, length);
```

**Comment by G4lile0** [comment]
Thanks for the feedback, it was already fixed on the beta branch, #110
