### ISSUE TITLE
add support for ESP32 Wem*s Lolin32 board with different I2C pins

### ISSUE THREAD

**Issue by eriktheV-king** [G4lile0/tinyGS#22]
May I suggest support for WeM*s Lolin32 (also known as avriant of Dduino32 or NodeMCU32)? i'm using this to test SX126x, but had to add different I2C pins, as they are different from TTGO and Heltec boards.
The WeM*s Lolin32 is a ESP32 board with no LoRa module, but with the SSD1306 display on address 0x3c, SDA: GPIO 5, SCL: GPIO 4. 
Keep up the good work and thank you!

**Comment by 4m1g0** [comment]
Thanks

Now the firmware supports custom templates to allow to configure any type of board without code modifications. If you make a template and you want to share it here we will add it to the examples on the wiki!
