### ISSUE TITLE
Add support for WebSerial Monitor

### ISSUE THREAD

**Issue by fooons** [G4lile0/tinyGS#45]
I wonder if this improvement/enhancement could be added to our GroundStations to be able to send commands to the web serial port and receive.  Unfortunately my TTGO crashed and I have lost the USB port.  I upload the software via Arduino and the network port.  I can solder some small cables, but for those of us who have had this breakdown or those who do not have the station nearby, it would be a great advance.

I have seen in GitHub a Remote Serial monitor for ESP8266 & ESP32 and I'm trying to use it, but until new board with USB arrives I'm not sure to program mine with changes.

Thanks in advance

**Comment by fooons** [comment]
Better than WebSerial I have used a Telnet server to monitor some messages and use the controls menu to erase and reboot in my home network. It has been a quick implementation so needs polish.
![Captura de pantalla 2020-11-09 a las 20 45 11](https://user-images.githubusercontent.com/11136798/98589285-5420ae00-22cd-11eb-8169-420642b85e29.png)

**Comment by hjf** [comment]
have you uploaded this code somewhere?

**Comment by 4m1g0** [comment]
Thanks for the suggestion.

Added web console on @21021701 

https://github.com/G4lile0/tinyGS/wiki/Local-Dashboard
