### ISSUE TITLE
It appears the position of the satellite shown on the Heltec display is off by one orbit

### ISSUE THREAD

**Issue by fraab** [G4lile0/tinyGS#51]
On my new station (KK6NOW - Palm Desert, CA, US),  I noticed that the position of the satellite shown on the Heltec display appears to be one orbit to the east of the position shown by Obritron, SatPC32 and the webpage fossa.apaluba.com/worldmap/  My timezone is set correctly and the time is correct.

Is this just a display problem?  Or does it cause a problem with the scheduling of an observation?  I have successfully received and uploaded one observation the day I setup the station.

**Comment by 4m1g0** [comment]
I cannot confirm this issue. Is it still happening in release @21021701 ?
