### ISSUE TITLE
OLED w/o RST pin

### ISSUE THREAD

**Issue by sacculus** [G4lile0/tinyGS#76]
Hi
I made custom station based on LOLIN32 board with 0.96" OLED display which doesn't have RST pin. Station works fine - I can open WEB-interface and see OK state at dashboard, but OLED doesn't show anything, screen is black.
I'm suppose that I2C connection works and OLED initializing properly because display blinks short time with some picture at moment when board restarts.
Is it possible to force to work my kind of OLED display?

**Comment by jhm776** [comment]
I'm using two different OLEDs that don't have a reset pin, both work OK. Does your display go blank after this screen? (This same issue showed up on my GS about a week ago, upgrading to newest TinyGS-master does not resolve this problem for me)
(is this some MQTT server issue???? - TinyGS code has not changed but this issue popped up)
Link to photo of my display  [https://imgur.com/gallery/VgvOwVe](url)

**Comment by sacculus** [comment]
Hi
I flashed my GS again and display started to work normally. Strange behavior, but I suppose that it would be possible because bad wiring with breadboard.
Pls, close issue with not a bug.
Thanks!
