### ISSUE TITLE
High current consumption

### ISSUE THREAD

**Issue by volodink** [G4lile0/tinyGS#85]
I think it would be great to send the esp to the sleep whenever its possible.
Just tested the last release and its i believe does not send the board to the sleep mode at all, cause it is hot like hell. 
I think there is no need to having constantle wifi on and lora modules can wake up esp as te signal arrives. 
Also, the screen enable could be in the dashboard, so you can lower consumtion by switching it off, maybe even permanently.

**Comment by 4m1g0** [comment]
I'll merge these 2 issues: https://github.com/G4lile0/tinyGS/issues/83
