### ISSUE TITLE
Inconsistent response value in MQTT message 

### ISSUE THREAD

**Issue by McOrts** [G4lile0/tinyGS#89]
Only when the satellite is UNKNOWN the last attribute is separated by _: "CRC_ERROR"
In all other cases, there is a space: "CRC ERROR".

[[1,0,0,0,"UNKNOWN"],[1,0,0,11,"Last Packet:   18:21"],[1,0,0,23,"RSSI/SNR:-131.0/-15.0dB"],[1,2,64,34,"Freq error: 1407.19Hz"],[1,2,64,45,"CRC_ERROR"]]

[[1,0,0,0,"Norby"],[1,0,0,11,"Last Packet:   18:21"],[1,0,0,23,"RSSI/SNR:-131.0/-15.0dB"],[1,2,64,34,"Freq error: 1407.19Hz"],[1,2,64,45,"CRC ERROR"]]

**Comment by 4m1g0** [comment]
Fixed, thanks!
