### ISSUE TITLE
Rescue mode button long press

### ISSUE THREAD

**Issue by DroneMechanic** [G4lile0/tinyGS#96]
Custom Esp32devkit v1 + RA02 - the long press seems to be on all the time. After the fw update keeps cycling into the local AP mode. 
Which pin number is being tested as the user button pinout?

My mappings:
Progbutton : 0
Board led :25
Sx127x :1
Nss : 15
Dio0 : 2
Dio1 : 5
Bussy :0
Rst : 9
Miso : 19
Mosi : 23
Sck : 18

Is one of my pins being used for the user button press?

I changed the progbutton to another empty gpio 34.
So far it hasnt done the phantom button press.

Also stopped using gpio 6-11 as it is used by the integrated spi flash and not recommended for other uses.
Also not using gpio 2 as this was the onboard led.
Also not using gpio 9 as mentioned above.

My new gpio mappings:
Progbutton : 34
Board led :2
Sx127x :1
Nss : 15
Dio0 : 4
Dio1 : 5
Bussy :0
Rst : 14
Miso : 19
Mosi : 23
Sck : 18

**Comment by doismellburning** [comment]
@DroneMechanic You closed this without any commentary, but I find myself having the same issue (TTGO T-Beam) - anything you could share please?

**Comment by doismellburning** [comment]
Actually I think 813c6c3621e7efa7f2c76d44d7d258dc3bf86552 (or something between then and 2104210) has fixed things for me

**Comment by letBulochkin** [comment]
I am stuck with the same problem, using TTGO T-Beam 868/915MHz with OLED. After setting up wi-fi settings my board connects to mny wi-fi for several seconds, then "Rescue mode forced by button long press!" message appears in the logs, and board resets to its inner AP. Firmware version 2105262, so it seems commit sent by @doismellburning didn't fix it.

**Comment by benjaminemhf** [comment]
I've had the same issue with various standalone ESP32 DevKits. It only occurred when they were connected to my PC via USB, and it forced the rescue mode every single time. Changing the Progbutton/pBut pin and grounding it didn't help. The solution was powering the ESP32 with any other source; via USB charger or via the 5 V/3.3 V pins directly. I think having it connected to the PC forces the ESP's "boot" mode on power-on and tinyGS somehow interprets that as a long press on pin 0.

**Comment by a-kalmykov** [comment]
I found the following things related to **T-Beam 1.1 868/915Mhz (SX1276 + NEO-6M GPS + OLED)**:
1. The correct value for `PROG__BUTTON` is `38`
2. The `INPUT_PULLUP` setting should be disabled for this board except the case with sleep mode (according to Meshtastic firmware sources)

**How to fix:**
1. Replace `INPUT_PULLUP` with `INPUT` in `tinyGS/tinyGS.ino` on the line `163`:
```c
// make sure to call doLoop at least once before starting to use the configManager
configManager.doLoop();
pinMode (configManager.getBoardConfig().PROG__BUTTON, INPUT);  // <-- here
displayInit();
```
2. Rebuild and upload to the board
3. Use the following Board Template (the `PROG__BUTTON` value here is 5th in order):
`{0x3c, 21, 22, 16, 38, 22, 1, 18, 26, 33, 32, 14, 19, 27, 5, 0.0f, "868-915Mhz T-BEAM 1.1 + OLED - Alt Prg Btn"}`
